[settings]
experimental = true
legacy_version_file = true
npm.package_manager = "aube"

[tools]
deno = "latest"
bun = "latest"
elixir = "latest"
erlang = "latest"
go = "latest"
node = "latest"
"npm:pnpm" = "latest"
usage = "latest"
uv = "latest"
aube = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
herdr = "latest"

